### ISSUE TITLE
Teamspeak server connection error

### ISSUE THREAD

**Issue by AMGitsKriss** [AMGitsKriss/Orion-Dashboard#40]
Fatal error: Uncaught TeamSpeak3_Transport_Exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. in C:\xampp\htdocs\libraries\TeamSpeak3\Transport\TCP.php:54 Stack trace: #0 C:\xampp\htdocs\libraries\TeamSpeak3\Transport\TCP.php(108): TeamSpeak3_Transport_TCP->connect() #1 C:\xampp\htdocs\libraries\TeamSpeak3\Adapter\ServerQuery.php(76): TeamSpeak3_Transport_TCP->readLine() #2 C:\xampp\htdocs\libraries\TeamSpeak3\Adapter\Abstract.php(60): TeamSpeak3_Adapter_ServerQuery->syn() #3 C:\xampp\htdocs\libraries\TeamSpeak3\TeamSpeak3.php(322): TeamSpeak3_Adapter_Abstract->__construct(Array) #4 C:\xampp\htdocs\controllers\home.php(84): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri)) #5 C:\xampp\htdocs\controllers\home.php(50): updateTS3Cache('USEr', 'PASSWORD') #6 C:\xampp\htdocs\_index.php(73): include_once('C:\\xampp\\htdocs...') #7 {main} thrown in C:\xampp\htdocs\libraries\TeamSpeak3\Transport\TCP.php on line 54

**Comment by AMGitsKriss** [comment]
Error results for server hostname connection. This needs to take the master $host variable, sans the "http://"
